### ISSUE TITLE
Разбираемся с циклом for

### ISSUE THREAD

**Issue by egpro** [bigman212/fogstream_tasks#2]
https://github.com/bigman212/fogstream_tasks/blob/43fc6193046eab6237c5a1a99505c66c144d0a3d/lection_2/task_2_solution_2.py#L24

Как можно упростить цикл, чтобы в теле цикла не тащить с собой индексы?

**Comment by bigman212** [comment]
Была идея сравнивать каждый элемент с последним, и при несовпадении сразу break. Но это не думаю что хорошее решение.
